# config_template.yaml (v2 — ÚNICA FONTE)
normalization:
  lowercase: true
  strip_accents: true
window: 8

matchers:
  positives:
    - pattern: "luva"
      type: literal
      weight: 2.0
    - pattern: "alicate"
      type: literal
      weight: 1.5

  negatives:
    - pattern: "moinho de martelos"
      type: phrase
      weight: 2.0

  contexts:
    MAOS:
      category: "Proteção das Mãos"
      patterns:
        - pattern: "mãos"
          type: literal
        - pattern: "mao"
          type: literal
        - pattern: "dedos"
          type: literal

rules:
  - name: incluir_maos_ferramenta
    equation: "WITHIN(8, POS(), CTX('MAOS')) and not CTX('EQUIPAMENTOS_BLOQUEIO')"
    decision: INCLUI
    min_score: 1.0
    assign_category: "Segurança > Proteção das Mãos"

  - name: excluir_negativos
    equation: "NEG()"
    decision: EXCLUI

  - name: revisar_padrao
    equation: "POS() or CTX('MAOS')"
    decision: REVISA
